[general]
import = ["~/.cache/wal/alacritty.toml"]

[font]
size = 10.0

[font.bold]
family = "JuliaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JuliaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JuliaMono Nerd Font"
style = "Italic"

[font.normal]
family = "JuliaMono Nerd Font"
style = "Regular"
