#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Config file for berry WM

## Berry Configs -----------------------------------------------

# Set decoration geometry
berryc border_width 		0
berryc inner_border_width 	4
berryc title_height 		14
# berryc top_gap 			10
berryc edge_gap 			42 4 4 4

# Set decoration colors
berryc focus_color 			292D3E
berryc unfocus_color 		292D3E
berryc inner_focus_color 	D97E96
berryc inner_unfocus_color 	496886
berryc text_focus_color 	FFFFFF
berryc text_unfocus_color 	011826

# Other options
berryc set_font 			"Hack Nerd Font Mono"
berryc smart_place 			"true"
berryc draw_text 			"true"
berryc edge_lock 			"true"
berryc json_status 			"true"
berryc decorate_new 		"true"
berryc pointer_interval 	0
berryc manage 				Dialog|Toolbar|Menu|Splash|Utility 

berryc move_mask 			"mod4"
berryc move_button 			1
berryc resize_mask 			"mod4"
berryc resize_button 		3

## Autostart Programs ------------------------------------------
bash "$HOME"/.config/berry/scripts/berry_autostart
